name: Build and Package Extension

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # ou a versão que seu projeto usa
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔨 Build the project
        run: pnpm build

      - name: 📦 Generate Firefox .xpi package
        run: pnpm generate:firefox

      - name: 📤 Upload XPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: entardecer.xpi
          path: ./target/entardecer.xpi
